title: Renee Singh
logo: headshot.png
description: Hi, I’m Renee, and I’m a senior at the University of Washington double majoring in Informatics (Data Science) and Economics, graduating in Spring 2026. I’m currently exploring internships in data science, data engineering, data analytics, and business intelligence for Summer 2025. 
show_downloads: false
theme: jekyll-theme-minimal
