title: Renee Singh
logo: headshot.png
description: Hi, I’m Renee, and I’m a senior double majoring in Informatics - Data Science and Economics, graduating next Spring. I’m currently exploring internships for Summer 2025, and believe that I can drive strategic, data-driven decision-making through my initiative to take ownership of projects and emphasis on goal-oriented solutions.
show_downloads: false
theme: jekyll-theme-minimal
