title: Renee Singh
logo: headshot.png
description: Hi, I’m Renee, and I’m a senior double majoring in Informatics - Data Science and Economics, graduating next Spring. I’m passionate about bridging data and strategy by applying my technical and analytical expertise to solve complex business challenges. I’m currently exploring internships for Summer 2025, and believe that through my initiative to take ownership of projects, emphasizing goal-oriented solutions development, I can drive strategic, data-driven decision making.
show_downloads: false
theme: jekyll-theme-minimal
